#!/usr/bin/env bash
# Installing nginx (enginex).. en web_01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo su
echo 'Hello World!' > /var/www/html/index.html
exit
sudo service nginx start
