#!/usr/bin/env bash
# Installing nginx (enginex).. 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start01~
