#!/usr/bin/env bash
# Adding some instruction to install and access the servers

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello world" | sudo tee /var/www/html/index.html
str="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
str="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default
str="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$str/" /etc/nginx/nginx.conf
sudo service nginx start
