#!/usr/bin/env bash
# Make a configuration of a new HAproxy as load balancer

apt-get -y update
apt-get -y install haproxy=2.9.\*

echo '
frontend atlastex.tech
        bind 0:80
        default_backend myservers

backend myservers
        balance roundrobin
        server 433575-web-01 54.236.51.182:80
        server 433575-web-02 54.164.53.198:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
