#!/usr/bin/env bash
# EngineX running inside engineX
sudo systemctl stop nginx
sudo sed -i 's/user\s*.*;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen\s*.*;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
