#!/usr/bin/env bash
# EngineX running inside engineX
sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo pkill -o apache2
sudo -u nginx nginx -c /etc/nginx/nginx.conf
