#!/usr/bin/env bash

# Gracefully reloads Gunicorn.

# Obtain the process IDs (PIDs) of Gunicorn processes.
ps auxf | grep gunicorn | grep -v grep | awk '{print $2}' | while read -r pid; do
    # Send the HUP (hang up) signal to each Gunicorn process.
    kill -HUP "$pid"
done
